### ISSUE TITLE
Not working to set up

### ISSUE THREAD

**Issue by APayerl** [DSorlov/swemail#10]
I have tried both 1.0.3 and 1.0.2 using HACS but keep getting issues...

![Screenshot_20220311-184153.png](https://user-images.githubusercontent.com/6882326/157922772-353dba4e-99f7-4b89-a613-8994e9cfbfc2.png)
![Screenshot_20220311-184217.png](https://user-images.githubusercontent.com/6882326/157922789-f7bd0728-30cd-4697-8b05-30dc788c2882.png)

Is this repo tested with latest version of Home Assistant? (which I use)

**Comment by DSorlov** [comment]
Hi. I am running it on latest myself. Is this after upgrade or is it new install on latest?

**Comment by APayerl** [comment]
New install...
Also the configuration could use some work (like probably bugfix..)

Step 1
![bild](https://user-images.githubusercontent.com/6882326/157929676-8c115c1e-0941-4e11-8edd-66bcea883f58.png)

Step 2
Restart HA

Step 3
![bild](https://user-images.githubusercontent.com/6882326/157931894-102919c9-ef7e-455d-9c37-f7d0ebe2e23a.png)
![bild](https://user-images.githubusercontent.com/6882326/157932091-8f0376e6-ffe7-4075-a504-84453140a8ea.png)
![bild](https://user-images.githubusercontent.com/6882326/157932115-bac8dc6c-18e7-4b47-9518-1df530f96cfd.png)

Step 4
![bild](https://user-images.githubusercontent.com/6882326/157932165-64ce8e7a-5731-41fc-92bb-3004697eda5a.png)

**Comment by DSorlov** [comment]
Something looks real strange there. I just retried it and works like a charm here, but need to verify on my test env. Dev is not clean. Could you try and force-relod the front end? It might be a caching issue as it does not seem to fins the language resouces correctly...

**Comment by APayerl** [comment]
it's the same if I do it from the mobile app or the pc Web browser... Has ha a way of forcing a clea of Frontend?...

**Comment by APayerl** [comment]
Here is another interesting section from my logs...
![Screenshot_20220311-223317.png](https://user-images.githubusercontent.com/6882326/157973537-90dc5362-f908-4ef9-91e5-1f505e2e0de0.png)

**Comment by DSorlov** [comment]
Have you installed via hacs or manual?

**Comment by APayerl** [comment]
Every try has been using HACS

**Comment by APayerl** [comment]
Just tried a manual install with just copying all the files from your main branch and that worked!
But to install main using HACS did NOT work...
