### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by jake404** [DSorlov/swemail#13]
It would be great to get the delivery dates in the HA calendar.

**Comment by DSorlov** [comment]
Any suggestion on how this would be implemented? Today the API only provides us the current and next delivery date (for Citymail only the next one actually). Would this be updated each time a new delivery is available? I am open for the idea but unsure how to implement..

**Comment by jake404** [comment]
I solved it by using the 'Entities Calendar' integration And with that I can now get notified of the next mail delivery in my 'Home Feed' in my dashboard.
