### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3

### ISSUE THREAD

**Issue by KentEkl** [DSorlov/swemail#16]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 17:04:41 (1 occurrences)
Last logged: 17:04:41

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for swemail using this method at custom_components/swemail/__init__.py, line 53: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by DSorlov** [comment]
Hi. See the same in my install. Will need to fix, due to time constraint I have some resource limitations right now but will be prioritized and if someone is interested please go ahead and submit a PR for the fun and glory of it all! =)

**Comment by KentEkl** [comment]
Hi, I don't now how to submit a PR but I changed the code locally and the errormsg disappered.
I don't know if I did it right but it seems to work,
Changed line 53 in __init__.py
from 
hass.config_entries.async_setup_platforms(entry, PLATFORMS) 
to 
await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
