### ISSUE TITLE
nytt postnummer

### ISSUE THREAD

**Issue by razzietheman** [DSorlov/swemail#17]
Från idag den 6/3 har vi fått nytt postnummer , men integrationen visar bara det nya som otillgängligt!

Söker man på postnumret https://www.postnord.se/vara-verktyg/sok-postnummer-och-adress?countryCode=SE&query=54964

det gick tidigare under 54164

så vad kan vara fel?

**Comment by DSorlov** [comment]
Jag får siffran n/a från API. Dvs datakällan hos PostNord säger att det inte finns tillgänglig data. Tyvärr inget jag kan göra något utan det beror på det underliggande APIt från PostNord. Kan bara hoppas att det är för att de ännu inte lagt in data i systemet för det postnummret och att det kommer igång snart.
