### ISSUE TITLE
Svensk Postutdelning doesn't work in HA with IPv6

### ISSUE THREAD

**Issue by nrehn** [DSorlov/swemail#27]
Svensk Postutdelning doesn't work in HA with native IPv6 address.

**Comment by DSorlov** [comment]
Need errorlogs etc to determine errors. Something more than "do not work"

**Comment by nrehn** [comment]
I believe the integration just doesn't support dualstack. 
But it don't even start up. 
But I will try give you logs of basically nothing:)

**Comment by nrehn** [comment]
Hi, I think you can close this issue. I have found some issues with DNS resolving which is not related to HA..
