### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by r0l01** [DSorlov/swemail#28]
The last couple of days I noticed that there seems to be some issue with the sensors not updating properly.

Sometimes the entities are shown as unavailable but after reloading values are populated. However they don't reflect the values I get when manually looking at postnord for my postal code.

I can't see any errors in the log file.

<img width="559" alt="Screenshot 2024-03-26 at 08 55 56" src="https://github.com/DSorlov/swemail/assets/44272889/e0fe688f-639c-4c74-9815-be028c380c43">

<img width="820" alt="Screenshot 2024-03-26 at 08 52 09" src="https://github.com/DSorlov/swemail/assets/44272889/03a76a7b-ba9f-4b42-906f-2ca0e64dc98e">

**Comment by DSorlov** [comment]
Have this error persisted?

**Comment by r0l01** [comment]
@DSorlov: No, it seemed to be solved by itself, so you can close the issue!

Have a nice day!
